server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: inventory-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/items,/api/items/**
          filters:
            - name: CircuitBreaker
              args:
                name: inventory-service
                fallbackUri: forward:/inventory-fallback
        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=0
            - name: CircuitBreaker
              args:
                name: product-service
                fallbackUri: forward:/product-fallback
        - id: billing-service
          uri: http://localhost:8082
          predicates:
            - Path=/**
          filters:
            - name: CircuitBreaker
              args:
                name: billing-service
                fallbackUri: forward:/billing-fallback

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      inventory-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
      product-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
      billing-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3