server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventorydb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
